### ISSUE TITLE
Removing Docker

### ISSUE THREAD

**Issue by michaeltieso** [simevo/spid-wordpress#21]
I don't think Docker is needed here. Testing can and should be done in any environment that the plugin supports. Any test scripts can be made separately and used on any WP install. For anyone that would like to continue to use Docker, install the basic WordPress Docker then install the plugin manually. No need to complicate this with our own Dockerfile. Thoughts?

**Comment by michaeltieso** [comment]
Hosting `spid-testenv2` will still need to be figured out. Websites may want to test before launching with SPID. Can we implement `spid-testenv2` within the plugin itself for website owners to test with before going live? This would need to be as simple as a check-mark in their settings.

**Comment by simevo** [comment]
I agree that this repo should only contain the plugin and its unit tests (i.e. tests that do not require a SPID IdP).
I agree that we should move the docker stuff to https://github.com/simevo/spid-wordpress-example-form ([same as for the ansible stuff](https://github.com/simevo/spid-wordpress/pull/19#issuecomment-431295264)).

Once we have all that in spid-wordpress-example-form, by leveraging the docker-compose we can add integration tests (i.e. tests that do require a SPID IdP) such as testing a complete round-trip incuding:
- first login
- user creation / check that requested attributes are receieved as user meta in WP
- logout
- change attribute in IdP / second login / check that attributes are updated in WP

For spid-php-lib-example we wrote a similar (but simpler) round-trip test using `Goutte\Client`, see: https://github.com/simevo/spid-php-lib-example/blob/master/tests/LoginTest.php

Finally we can then set up travis CI as we did for spid-php-lib-example (see https://github.com/simevo/spid-php-lib-example/blob/master/.travis.yml and https://travis-ci.com/simevo/spid-php-lib-example). There is no need to host spid-testenv2 since that and will run in an ephemeral container spun off by docker-compose on the Travis CI infrastructure.

So go ahead with pruning docker stuff from here !

**Comment by simevo** [comment]
While rewiewing PR #20 I found very useful to still have the docker setup in place in this repo.

At least while we're in the turbulent initial phase of significant changes and refactorings I would keep the docker around.

This issue is very fast to fix with `rm -rf docker` and clean up the README so I'd keep it as last before we tag the first release !

**Comment by michaeltieso** [comment]
You can still use Docker independently of this plugin.
